# SPDX-FileCopyrightText: 2021-2023 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Helsinki"
    allow:
      - dependency-name: "adobe/s3mock"
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Helsinki"
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major", "version-update:semver-patch" ]
    groups:
      jest:
        patterns:
          - "@types/jest"
          - "jest*"
          - "ts-jest"
        exclude-patterns:
          - "jest-junit"
      typescript:
        patterns:
          - "tslib"
          - "typescript"
  - package-ecosystem: "terraform"
    directory: "/infra/deploy"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "gradle"
    directory: "/service"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Helsinki"
    ignore:
      - dependency-name: "com.sun.xml.bind:jaxb-xjc"
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
