# SPDX-FileCopyrightText: 2021-2023 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/auth"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gradle"
    directory: "/mock/identification"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot"
      - dependency-name: "jvm"
      - dependency-name: "plugin.spring"
  - package-ecosystem: "gradle"
    directory: "/service"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jetbrains.kotlin.jvm"
      - dependency-name: "org.jetbrains.kotlin.plugin.spring"
      - dependency-name: "org.springframework.boot"
      - dependency-name: "com.sun.xml.bind:jaxb-xjc"
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
