# SPDX-FileCopyrightText: 2023 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    url: jdbc:postgresql://localhost:5432/evaka_vesilahti_local
    flyway:
      locations: db/migration,db/data/vesilahti
  oph:
    organizer_oid: "1.2.246.562.10.81321154148"
    organizer_id: "todo"
    municipality_code: "922"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Vesilahti"
        street_address: "TODO"
        postal_code: "TODO"
        post_office: "Vesilahti"
