# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/kangasala
  oph:
    organizer_oid: "1.2.246.562.10.67543287985"
    organizer_id: "todo"
    municipality_code: "123"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Kangasala"
        street_address: "PL 50"
        postal_code: "36201"
        post_office: "Kangasala"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: kangasala
