# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/pirkkala
  oph:
    organizer_oid: "1.2.246.562.10.54675287985"
    organizer_id: "todo"
    municipality_code: "604"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Pirkkala"
        street_address: "PL 1001"
        postal_code: "33961"
        post_office: "Pirkkala"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: pirkkala
