# SPDX-FileCopyrightText: 2023 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/vesilahti
  oph:
    organizer_oid: "1.2.246.562.10.81321154148"
    organizer_id: "240"
    municipality_code: "922"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Vesilahti"
        street_address: "Rautialantie 60"
        postal_code: "37470"
        post_office: "Vesilahti"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: vesilahti
