# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/ylojarvi
  oph:
    organizer_oid: "1.2.246.562.10.74495287985"
    organizer_id: "todo"
    municipality_code: "980"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Ylöjärvi"
        street_address: "Kuruntie 14"
        postal_code: "33470"
        post_office: "Ylöjärvi"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: ylojarvi
