# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/lempaala
  oph:
    organizer_oid: "1.2.246.562.10.74484103937"
    organizer_id: "todo"
    municipality_code: "418"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Lempäälä"
        street_address: "PL 36"
        postal_code: "37501"
        post_office: "Lempäälä"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: lempaala
