# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/nokia
  oph:
    organizer_oid: "1.2.246.562.10.95000650127"
    organizer_id: "93"
    municipality_code: "536"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Nokia"
        street_address: "Harjukatu 23"
        postal_code: "37100"
        post_office: "Nokia"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: nokia
nokia:
  invoice:
    municipalityCode: 536
    invoiceType: 56
