# SPDX-FileCopyrightText: 2023 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    url: jdbc:postgresql://localhost:5432/evaka_hameenkyro_local
    flyway:
      locations: db/migration,db/data/hameenkyro
  oph:
    organizer_oid: "1.2.246.562.10.64495287985"
    organizer_id: "todo"
    municipality_code: "108"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Hämeenkyrö"
        street_address: "TODO"
        postal_code: "TODO"
        post_office: "Hämeenkyrö"
