# SPDX-FileCopyrightText: 2024 Tampere region
#
# SPDX-License-Identifier: LGPL-2.1-or-later

evaka:
  database:
    flyway:
      locations: db/migration,db/data/orivesi
  oph:
    organizer_oid: "1.2.246.562.10.74499914872"
    organizer_id: "246"
    municipality_code: "562"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Orivesi"
        street_address: "PL 7"
        postal_code: "35301"
        post_office: "Orivesi"
  planned_absence:
    enabled_for_hour_based_service_needs: true
trevaka:
  municipality: orivesi
orivesi:
  invoice:
    municipalityCode: 562
    invoiceType: 54
