# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Docker compose for creating local dev databases
#
version: '3.5'

services:
  db:
    build: ../evaka/compose/db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5

  db_it:
    build: ../evaka/compose/db-integration-test
    ports:
      - "15432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(redis-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5

  s3.mock.evaka:
    image: adobe/s3mock
    ports:
      - "9090:9090"
      - "9876:9090" # for core tests
    volumes:
      - s3-data:/data
    environment:
      ROOT: /data
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090" ]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
