version: '3.8'

services:
  auth:
    build: ../auth
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    depends_on:
      - smtp
  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
