# SPDX-FileCopyrightText: 2021-2022 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: "3.5"

services:
  playwright:
    image: trevaka/e2e-playwright:latest
    build:
      context: ./e2e
      dockerfile: ./playwright.Dockerfile
    volumes:
      - ..:/repo
    ipc: host
    environment:
      HEADLESS: ${HEADLESS:-true}
      DEBUG: ${DEBUG:-}
