# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Use this compose file to extend docker-compose.yml when you want to run
# the latest published versions, e.g. for E2E testing.
#
# Scavenged from evaka integration testing and e2e compose files

version: '3.5'

services:
  evaka-proxy:
    image: ${EVAKA_FRONTEND_IMAGE}
    ports:
      - "9999:8080"
    environment:
      RESOLVER: "127.0.0.11 ipv6=off"
      ENDUSER_GW_URL: "http://enduser-gw:3010"
      INTERNAL_GW_URL: "http://internal-gw:3020"
      STATIC_FILES_ENDPOINT_URL: "http://s3.mock.evaka:9090/static/frontend"
      RATE_LIMIT_CIDR_WHITELIST: "0.0.0.0/0;::/0"
      HTTP_SCHEME: "http"
    # Enable for debug logging
    # command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - enduser-gw
      - internal-gw
      - trevaka-srv
      - s3.mock.evaka

  enduser-gw:
    image: ${EVAKA_GW_IMAGE}
    ports:
      - "3010"
    hostname: enduser-gw
    depends_on:
      - redis
    volumes:
      - ../evaka/apigw/config/test-cert:/home/evaka/test-cert
    env_file:
      - .env
    environment:
      VOLTTI_ENV: local
      NODE_ENV: local
      GATEWAY_ROLE: enduser
      EVAKA_SERVICE_URL: ${EVAKA_SERVICE_URL}
      COOKIE_SECRET: cookie_secret
      REDIS_HOST: ${EVAKA_REDIS_HOST}
      REDIS_PORT: ${EVAKA_REDIS_PORT}
      REDIS_DISABLE_SECURITY: "true"
      JWT_PRIVATE_KEY: /home/evaka/test-cert/jwt_private_key.pem
      EVAKA_CUSTOMER_SAML_PUBLIC_CERT: /home/evaka/test-cert/keycloak-local.pem
      EVAKA_CUSTOMER_SAML_PRIVATE_CERT: /home/evaka/test-cert/saml-private.pem
      ENABLE_DEV_API: "true"
      PRETTY_LOGS: "false"

  internal-gw:
    image: ${EVAKA_GW_IMAGE}
    ports:
      - "3020"
    hostname: internal-gw
    depends_on:
      - redis
    volumes:
      - ../evaka/apigw/config/test-cert:/home/evaka/test-cert
    environment:
      VOLTTI_ENV: local
      NODE_ENV: local
      GATEWAY_ROLE: internal
      EVAKA_SERVICE_URL: ${EVAKA_SERVICE_URL}
      COOKIE_SECRET: cookie_secret
      REDIS_HOST: ${EVAKA_REDIS_HOST}
      REDIS_PORT: ${EVAKA_REDIS_PORT}
      REDIS_DISABLE_SECURITY: "true"
      JWT_PRIVATE_KEY: /home/evaka/test-cert/jwt_private_key.pem
      EVAKA_SAML_PUBLIC_CERT: /home/evaka/test-cert/keycloak-local.pem
      EVAKA_SAML_PRIVATE_CERT: /home/evaka/test-cert/saml-private.pem
      ENABLE_DEV_API: "true"
      PRETTY_LOGS: "false"

volumes:
  db-data:
    driver: local
