#!/bin/sh -e

# SPDX-FileCopyrightText: 2021 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Scavenged from evaka integration testing and e2e compose files

export UID="${UID:-$(id -u)}"
export GID="${GID:-$(id -g)}"

docker-compose -f docker-compose.yml -f docker-compose.e2e.yml -f docker-compose.e2e-tests.yml run playwright
